### ISSUE TITLE
Uncaught TypeError: window.phetSplashScreenDownloadComplete is not a function

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/blackbody-spectrum#14]
```
blackbody-spectrum
Uncaught TypeError: window.phetSplashScreenDownloadComplete is not a function
TypeError: window.phetSplashScreenDownloadComplete is not a function
    at new Sim (http://localhost:8080/joist/js/Sim.js?bust=1512766634435:77:12)
    at http://localhost:8080/blackbody-spectrum/js/blackbody-spectrum-main.js?bust=1512766634435:32:15
    at window.phetLaunchSimulation (http://localhost:8080/joist/js/SimLauncher.js?bust=1512766634435:47:11)
    at doneLoadingImages (http://localhost:8080/joist/js/SimLauncher.js?bust=1512766634435:69:18)
    at Object.launch (http://localhost:8080/joist/js/SimLauncher.js?bust=1512766634435:123:9)
    at http://localhost:8080/blackbody-spectrum/js/blackbody-spectrum-main.js?bust=1512766634435:31:15
    at Object.execCb (http://localhost:8080/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (http://localhost:8080/sherpa/lib/require-2.1.11.js:866:35)
    at Module. (http://localhost:8080/sherpa/lib/require-2.1.11.js:1113:20)
    at http://localhost:8080/sherpa/lib/require-2.1.11.js:132:17
```

caught while running test-server. Sim not in active-runnables so it isn't showing up in continuous testing.

**Comment by samreid** [comment]
Fixed, closing.
