### ISSUE TITLE
CT no such file or directory

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#84]
```
blackbody-spectrum : build : phet
Failure to grunt snapshot-1551826170170/blackbody-spectrum:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (blackbody-spectrum, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1551826170170/blackbody-spectrum/js/blackbodyConstants.js'
In module tree:
    blackbody-spectrum-main
      BLACKBODY_SPECTRUM/blackbody-spectrum/BlackbodySpectrumScreen
        BLACKBODY_SPECTRUM/blackbody-spectrum/model/BlackbodySpectrumModel

  at /data/share/phet/continuous-testing/snapshot-1551826170170/chipper/js/grunt/requireBuild.js:107:15
  at /data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1551826170170/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 3/5/2019, 3:49:30 PM
blackbody-spectrum : build : phet-io
Failure to grunt snapshot-1551826170170-phet-io/blackbody-spectrum:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (blackbody-spectrum, brands: phet, phet-io)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/blackbody-spectrum/js/blackbodyConstants.js'
In module tree:
    blackbody-spectrum-main
      BLACKBODY_SPECTRUM/blackbody-spectrum/BlackbodySpectrumScreen
        BLACKBODY_SPECTRUM/blackbody-spectrum/model/BlackbodySpectrumModel

  at /data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/js/grunt/requireBuild.js:107:15
  at /data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1551826170170-phet-io/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 3/5/2019, 3:49:30 PM
blackbody-spectrum : fuzz : require.js-canvas : load
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Script error for: BLACKBODY_SPECTRUM/blackbodyConstants
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: BLACKBODY_SPECTRUM/blackbodyConstants
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1551826170170/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1551826170170/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/5/2019, 3:49:30 PM
blackbody-spectrum : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Script error for: BLACKBODY_SPECTRUM/blackbodyConstants
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: BLACKBODY_SPECTRUM/blackbodyConstants
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1551826170170/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1551826170170/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/5/2019, 3:49:30 PM
blackbody-spectrum : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: blackbody-spectrum: event indexing failed:
Uncaught Error: Uncaught Error: Script error for: BLACKBODY_SPECTRUM/blackbodyConstants
http://requirejs.org/docs/errors.html#scripterror
https://bayes.colorado.edu/continuous-testing/snapshot-1551826170170/phet-io-wrappers/js/tests/SimTests.js?bust=1551827486812:484


id: Bayes Chrome
Approximately 3/5/2019, 3:49:30 PM
blackbody-spectrum : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Script error for: BLACKBODY_SPECTRUM/blackbodyConstants
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: BLACKBODY_SPECTRUM/blackbodyConstants
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1551826170170/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1551826170170/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/5/2019, 3:49:30 PM
blackbody-spectrum : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Script error for: BLACKBODY_SPECTRUM/blackbodyConstants
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: BLACKBODY_SPECTRUM/blackbodyConstants
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1551826170170/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1551826170170/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/5/2019, 3:49:30 PM
```

**Comment by chrisklus** [comment]
This was fixed in https://github.com/phetsims/blackbody-spectrum/commit/11b38b9039a1c0dbf6178281fc8d7b56d90c61f5, closing.
